import type { Lesson } from "../types";

export const numbersCounting: Lesson = {
  id: "numbers-counting",
  stage: "n5",
  order: 13,
  title: "Numbers & Counting",
  subtitle: "Counters · clock time · weekdays — schedules",
  summary:
    "Count things and people, tell the time with 時・分, name weekdays with 曜日 — enough to talk about trains and class schedules.",
  estMinutes: 20,
  vocabulary: [
    { word: "一[いち]", reading: "いち", meaning: "one" },
    { word: "十[じゅう]", reading: "じゅう", meaning: "ten" },
    { word: "百[ひゃく]", reading: "ひゃく", meaning: "hundred" },
    { word: "千[せん]", reading: "せん", meaning: "thousand" },
    { word: "万[まん]", reading: "まん", meaning: "ten thousand" },
    { word: "時[じ]", reading: "じ", meaning: "o'clock (hour counter)" },
    { word: "分[ふん/ぷん]", reading: "ふん", meaning: "minute" },
    { word: "曜日[ようび]", reading: "ようび", meaning: "day of the week" },
    { word: "二人[ふたり]", reading: "ふたり", meaning: "two people" },
    { word: "電車[でんしゃ]", reading: "でんしゃ", meaning: "train" },
    { word: "今[いま]", reading: "いま", meaning: "now" },
    { word: "八[はち]", reading: "はち", meaning: "eight" },
  ],
  blocks: [
    {
      type: "prose",
      text: "Schedules need **numbers**, **counters**, **clock time**, and **weekdays**. Japanese counts in groups of four digits for large numbers ({{万}} = 10,000), and attaches counters after the number — not before the noun like English 'two tickets'.",
    },
    {
      type: "heading",
      text: "Core numbers",
    },
    {
      type: "table",
      caption: "1–10 and big units",
      headers: ["Value", "Kanji", "Reading"],
      rows: [
        ["1", "一", "いち"],
        ["2", "二", "に"],
        ["3", "三", "さん"],
        ["4", "四", "よん / し"],
        ["5", "五", "ご"],
        ["6", "六", "ろく"],
        ["7", "七", "なな / しち"],
        ["8", "八", "はち"],
        ["9", "九", "きゅう / く"],
        ["10", "十", "じゅう"],
        ["100", "百", "ひゃく"],
        ["1000", "千", "せん"],
        ["10000", "万", "まん"],
      ],
    },
    {
      type: "note",
      text: "After 10, prefer {{よん}} over {{し}} and {{なな}} over {{しち}} in most counting. Sound changes appear in hundreds: {{三百}} = さんびゃく, {{六百}} = ろっぴゃく, {{八百}} = はっぴゃく.",
    },
    {
      type: "heading",
      text: "Counters",
    },
    {
      type: "rule",
      title: "Number + counter",
      items: [
        "Generic things: {{〜つ}} ({{一つ}}, {{二つ}}… {{九つ}}, then {{十}}).",
        "People: {{〜人}} — but {{一人[ひとり]}}, {{二人[ふたり]}}, then {{三人[さんにん]}}…",
        "Flat objects (tickets, paper): {{〜枚[まい]}}",
        "Long objects (pens, bottles): {{〜本[ほん]}} (readings shift: いっぽん, さんぼん…)",
      ],
    },
    {
      type: "examples",
      title: "At the ticket machine",
      items: [
        { jp: "切符[きっぷ]を二[に]枚[まい]ください。", en: "Two tickets, please." },
        { jp: "三人[さんにん]です。", en: "(There are) three people." },
        { jp: "水[みず]を一[いっ]本[ぽん]ください。", en: "One bottle of water, please." },
      ],
    },
    {
      type: "heading",
      text: "Clock time — 時 and 分",
    },
    {
      type: "rule",
      title: "Hours and minutes",
      items: [
        "Hour: number + {{時[じ]}} — {{三時}} (3:00), {{七時}} (often しちじ), {{九時}} (くじ)",
        "Minutes: number + {{分[ふん/ぷん]}} — {{五分}} (ごふん), {{十分}} (じゅっぷん / じっぷん)",
        "Half past: {{〜時半[はん]}} — {{七時半}} (7:30)",
        "a.m. / p.m.: {{午前[ごぜん]}} / {{午後[ごご]}} before the time",
      ],
    },
    {
      type: "table",
      caption: "Handy times for commuting",
      headers: ["Japanese", "Meaning"],
      rows: [
        ["八時", "8:00"],
        ["八時十五分", "8:15"],
        ["八時半", "8:30"],
        ["九時五分", "9:05"],
        ["午前七時", "7:00 a.m."],
        ["午後六時", "6:00 p.m."],
      ],
    },
    {
      type: "examples",
      items: [
        { jp: "電車[でんしゃ]は八[はち]時[じ]です。", en: "The train is at 8:00." },
        { jp: "会議[かいぎ]は十[じゅう]時[じ]半[はん]からです。", en: "The meeting is from 10:30." },
        { jp: "今[いま]三[さん]時[じ]十五[じゅうご]分[ふん]です。", en: "It is 3:15 now." },
      ],
    },
    {
      type: "heading",
      text: "Weekdays — 曜日",
    },
    {
      type: "table",
      caption: "Days of the week",
      headers: ["Day", "Japanese", "Reading"],
      rows: [
        ["Monday", "月曜日", "げつようび"],
        ["Tuesday", "火曜日", "かようび"],
        ["Wednesday", "水曜日", "すいようび"],
        ["Thursday", "木曜日", "もくようび"],
        ["Friday", "金曜日", "きんようび"],
        ["Saturday", "土曜日", "どようび"],
        ["Sunday", "日曜日", "にちようび"],
      ],
    },
    {
      type: "examples",
      title: "Schedule talk",
      items: [
        { jp: "月曜日[げつようび]にテストがあります。", en: "There is a test on Monday." },
        { jp: "土曜日[どようび]は休[やす]みです。", en: "Saturday is a day off." },
        { jp: "金曜日[きんようび]の九[く]時[じ]に会[あ]いましょう。", en: "Let's meet at 9:00 on Friday." },
      ],
    },
    {
      type: "dialogue",
      title: "Checking the timetable",
      lines: [
        { speaker: "A", jp: "次[つぎ]の電車[でんしゃ]はいつですか。", en: "When is the next train?" },
        { speaker: "B", jp: "八[はち]時[じ]十五[じゅうご]分[ふん]です。", en: "It's at 8:15." },
        { speaker: "A", jp: "今日[きょう]は何曜日[なんようび]ですか。", en: "What day of the week is it today?" },
        { speaker: "B", jp: "水曜日[すいようび]です。", en: "It's Wednesday." },
      ],
    },
    {
      type: "tip",
      text: "{{何曜日}} asks 'what day (of the week)?'. {{何時}} asks 'what time?'. Both use {{なん}} before the counter-like word.",
    },
  ],
  quiz: [
    {
      kind: "mc",
      prompt: "How do you say 'two people'?",
      choices: ["二人 (ふたり)", "二人 (ににん)", "二個", "二つ人"],
      answer: 0,
      explanation: "一人=ひとり, 二人=ふたり (special readings).",
    },
    {
      kind: "mc",
      prompt: "八時半 means…",
      choices: ["8:00", "8:15", "8:30", "8:45"],
      answer: 2,
      explanation: "半 = half past → 8:30.",
    },
    {
      kind: "mc",
      prompt: "Which is Wednesday?",
      choices: ["月曜日", "水曜日", "金曜日", "日曜日"],
      answer: 1,
      explanation: "水曜日 = Wednesday (水 = water).",
    },
    {
      kind: "fill",
      prompt: "Type the reading of 万 (10,000):",
      answers: ["まん"],
      explanation: "万 = まん.",
    },
    {
      kind: "mc",
      prompt: "切符を二枚ください asks for…",
      choices: ["Two bottles", "Two tickets", "Two people", "Two o'clock"],
      answer: 1,
      explanation: "枚 counts flat objects like tickets.",
    },
    {
      kind: "order",
      prompt: "Build: 'The train is at 8:00'",
      tiles: ["電車[でんしゃ]は", "八[はち]時[じ]", "です"],
      distractors: ["八[はち]分[ふん]", "月曜日[げつようび]"],
      explanation: "Topic + hour + です.",
    },
  ],
  drills: [
    { id: "futari", prompt: "Say 'two people'", jp: "人[ひと]が二人", answers: ["二人[ふたり]", "ふたり"] },
    { id: "hachiji", prompt: "Say 8:00", jp: "8:00", answers: ["八[はち]時[じ]", "はちじ"] },
    { id: "han", prompt: "Say 7:30", jp: "7:30", answers: ["七[しち]時[じ]半[はん]", "しちじはん", "ななじはん"] },
    { id: "getsuyoubi", prompt: "Say Monday", jp: "Monday", answers: ["月曜日[げつようび]", "げつようび"] },
    { id: "nanji", prompt: "Ask 'what time?'", jp: "◯ですか", answers: ["何時[なんじ]", "なんじ"] },
    { id: "mai", prompt: "Fill the counter — two tickets", jp: "切符[きっぷ]を二[に]◯ください", answers: ["枚[まい]", "まい"] },
  ],
};
