/**
 * Regenerates content/audio-manifest.json — the list of every line the app
 * speaks, with stable clip ids for the natural-audio recording pass (2.5).
 *
 *   npm run audio:manifest
 */

import { writeFileSync } from "node:fs";
import { collectAudioLines } from "@/lib/audio-lines";

const lines = collectAudioLines();

const byCategory = new Map<string, number>();
for (const line of lines) {
  for (const source of line.sources) {
    const category = source.split(":")[0];
    byCategory.set(category, (byCategory.get(category) ?? 0) + 1);
  }
}

const manifest = {
  $comment:
    "Generated by `npm run audio:manifest` — do not edit. One entry per distinct utterance; record each as <id>.mp3 (planned home: public/audio/).",
  count: lines.length,
  lines,
};

const out = new URL("../content/audio-manifest.json", import.meta.url);
writeFileSync(out, JSON.stringify(manifest, null, 2) + "\n");

console.log(`audio-manifest: ${lines.length} distinct utterances`);
for (const [category, n] of [...byCategory].sort()) {
  console.log(`  ${category.padEnd(8)} ${n} source lines`);
}
